version: '3.8'

services:
  #Database
  mysql_db:
    image: mysql:8.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: local
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
      - mysql_db_data:/var/lib/mysql

  #Database client
  adminer:
    image: adminer:4.8.1
    container_name: adminer
    restart: unless-stopped
    environment:
      ADMINER_DEFAULT_SERVER: mysql_db
      ADMINER_DESIGN: dracula
    ports:
      - "7070:8080"
    expose:
      - "7070"
    deploy:
      resources:
        limits:
          memory: 30M

  #keyCloak
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    container_name: keycloak
    command:
      - start-dev
      - --import-realm
      - --health-enabled=true
    volumes:
      - ./docker/keycloak/realm-export.json:/opt/keycloak/data/import/realm.json
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8085:8080"

volumes:
  mysql_db_data:
